import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:mind_house_app/repositories/information_repository.dart';
import 'package:mind_house_app/repositories/tag_repository.dart';
import 'package:mind_house_app/database/database_helper.dart';

// This file is generated by running: flutter packages pub run build_runner build
// The generated file will be: mock_repositories.mocks.dart

@GenerateMocks([
  InformationRepository,
  TagRepository,
  DatabaseHelper,
])
void main() {
  // This file is used to generate mocks
  // Run: fvm flutter packages pub run build_runner build
}